In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")

In [3]:
data = pd.read_csv('Epileptic Seizure Recognition Data Set.csv')

In [4]:
data

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9  ...  X170  \
0      X21.V1.791  135  190  229  223  192  125   55   -9  -33  ...   -17   
1      X15.V1.924  386  382  356  331  320  315  307  272  244  ...   164   
2         X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85  ...    57   
3       X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87  ...   -82   
4       X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21  ...     4   
5       X14.V1.56   55   28   18   16   16   19   25   40   52  ...   -12   
6       X3.V1.191  -55   -9   52  111  135  129  103   72   37  ...  -125   
7      X11.V1.273    1   -2   -8  -11  -12  -17  -15  -16  -18  ...   -79   
8      X19.V1.874 -278 -246 -215 -191 -177 -167 -157 -139 -118  ...  -400   
9       X3.V1.491    8   15   13    3   -6   -8   -5    4   25  ...    49   
10        X3.V1.6   -5   15   28   28    9  -29  -41  -19   14  ...   -38   
11     X21.V1.724 -167 -230 -280 -315 -338 -369 -405 -392 -298  ...   423   
12      X7.V1.162   92   49    0  -32  -51  -65  -37  -19  -25  ...   -56   
13      X1.V1.211   15   12    0  -17  -28  -31  -39  -51  -44  ...   -88   
14      X1.V1.615  -24  -15   -5   -1    4    3    6   10   11  ...    32   
15     X22.V1.242 -135 -133 -125 -118 -111 -105 -102  -93  -94  ...   -49   
16      X1.V1.863   39   41   41   42   43   43   46   47   49  ...    43   
17      X9.V1.302    9    4   -5  -10  -22  -30  -33  -43  -41  ...    34   
18      X7.V1.541  -21   -5    1    7   19   20   13    2   -1  ...    43   
19      X9.V1.915    4   24   51   76   92  102  104  101   90  ...     3   
20     X23.V1.964  410  451  491  541  581  641  736  757  692  ...   415   
21      X1.V1.614  -24  -27  -23  -28  -34  -40  -47  -43  -38  ...   -81   
22     X11.V1.134 -264 -189 -117  -45   20   70  111  143  161  ...  -231   
23     X18.V1.544   -4   40   78  123  149  185  197  189  167  ...  -189   
24     X19.V1.294  593  328   88 -106 -456 -732 -921 -782 -522  ...   312   
25     X21.V1.802  -16  -15  -19  -16  -14   -5    0   -1   -3  ...    56   
26       X2.V1.72  -20  -38  -53  -58  -66  -66  -69  -77  -87  ...   -26   
27      X3.V1.744 -340 -381 -376 -336 -275 -204 -131  -70  -16  ...   114   
28     X12.V1.733  -30   15   61   80   72   41  -11  -31  -47  ...    -9   
29      X8.V1.614   -1   18   35   36   29   17   10    1   -3  ...    -6   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
11470  X17.V1.232  -62  -33   13   51   89  111  114  124  120  ...    34   
11471  X21.V1.334 -214 -320 -418 -534 -748 -638 -470   42  454  ...  1033   
11472   X5.V1.332  -61  -71  -77  -74  -74  -72  -72  -76  -77  ...   -51   
11473   X4.V1.173 -106 -133 -130 -111  -91  -62  -39    4   42  ...   -80   
11474    X8.V1.88  -50  -48  -63  -62  -46  -24   -1   13   27  ...    44   
11475   X7.V1.462  -68  -43  -24   -3  -15  -16  -15  -17  -19  ...    87   
11476  X22.V1.984 -293 -297 -302 -307 -318 -331 -347 -361 -369  ...    12   
11477  X10.V1.421   28   36   26    4  -35  -52  -51  -39  -12  ...     4   
11478   X3.V1.554  452  470  401  291  163   83   20  -32  -61  ...   182   
11479  X16.V1.353   62   68   75   75   75   77   81   85   82  ...    -1   
11480   X13.V1.26   26   33   31   26   31   40   49   61   61  ...     6   
11481   X8.V1.444  -86 -101 -115 -129 -139 -147 -154 -159 -165  ...   -39   
11482   X8.V1.904 -121    4  104  185  269  352  405  421  392  ...   339   
11483   X1.V1.902    7   30   16   10   17   23   42   31   34  ...   190   
11484  X13.V1.583  -18  -12   -5   -4   -3   -9  -16  -27  -35  ...   -63   
11485    X7.V1.81  -27   -8  -22  -48  -75  -99 -109 -105  -99  ...   -43   
11486  X15.V1.601    7  -28  -46  -45  -31    2   17   12   -2  ...    39   
11487  X17.V1.874   98  107  121  143  166  184  185  174  153  ...   -31   
11488  X20.V1.494  267  409  450  416  334  248  173  113   67  ...   413   
11489    X7.V1.51   90   83   69   41   31   40   58   75   82  ...    83   
114

# DATA DESCRPITION

we have 23 x 500 = 11500 pieces of information(row), each information contains 178 data points for 1 second(column), the last column represents the label y {1,2,3,4,5}.

The response variable is y in column 179, the Explanatory variables X1, X2, ..., X178

y contains the category of the 178-dimensional input vector. Specifically y in {1, 2, 3, 4, 5}:

5 - eyes open, means when they were recording the EEG signal of the brain the patient had their eyes open

4 - eyes closed, means when they were recording the EEG signal the patient had their eyes closed

3 - Yes they identify where the region of the tumor was in the brain and recording the EEG activity from the healthy brain area

2 - They recorder the EEG from the area where the tumor was located

1 - Recording of seizure activity 


All subjects falling in classes 2, 3, 4, and 5 are subjects who did not have epileptic seizure. Only subjects in class 1 have epileptic seizure.

In [ ]:
data.info

In [5]:
data.drop(data.columns[0], axis=1, inplace=True)

In [6]:
data.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...  X170  X171  X172  \
0  135  190  229  223  192  125   55   -9  -33  -38  ...   -17   -15   -31   
1  386  382  356  331  320  315  307  272  244  232  ...   164   150   146   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...    57    64    48   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...   -82   -81   -80   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59  ...     4     2   -12   

   X173  X174  X175  X176  X177  X178  y  
0   -77  -103  -127  -116   -83   -51  4  
1   152   157   156   154   143   129  1  
2    19   -12   -30   -35   -35   -36  5  
3   -77   -85   -77   -72   -69   -65  5  
4   -32   -41   -65   -83   -89   -73  5  

[5 rows x 179 columns]

In [7]:
data["OUTPUT_LABEL"] = data.y == 1
data["OUTPUT_LABEL"] = data["OUTPUT_LABEL"].astype(int)
data.pop('y')
data.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...  X170  X171  X172  \
0  135  190  229  223  192  125   55   -9  -33  -38  ...   -17   -15   -31   
1  386  382  356  331  320  315  307  272  244  232  ...   164   150   146   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...    57    64    48   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...   -82   -81   -80   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59  ...     4     2   -12   

   X173  X174  X175  X176  X177  X178  OUTPUT_LABEL  
0   -77  -103  -127  -116   -83   -51             0  
1   152   157   156   154   143   129             1  
2    19   -12   -30   -35   -35   -36             0  
3   -77   -85   -77   -72   -69   -65             0  
4   -32   -41   -65   -83   -89   -73             0  

[5 rows x 179 columns]

In [ ]:
#random forest
X = data.drop(['OUTPUT_LABEL'], axis = 1)
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

In [ ]:
#SVM 
X = data.drop(['OUTPUT_LABEL'], axis = 1)
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = data.drop(['OUTPUT_LABEL'], axis = 1)
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

In [8]:
import pywt

In [9]:
coeffs1 = pywt.wavedec(data , 'db7' , level = 1)
coeffs2 = pywt.wavedec(data , 'db7' , level = 2)
coeffs3 = pywt.wavedec(data , 'db7' , level = 3)
coeffs4 = pywt.wavedec(data , 'db7' , level = 4)
coeffs5= pywt.wavedec(data , 'db7' , level = 5)
coeffs6 = pywt.wavedec(data , 'db7' , level = 6)

In [10]:
print(len(coeffs1))
print(len(coeffs2))
print(len(coeffs3))
print(len(coeffs4))
print(len(coeffs5))
print(len(coeffs6))

2
3
4
5
6
7


In [11]:
# FOR LEVEL 1
l1a = pd.DataFrame(coeffs1[0])
l1b = pd.DataFrame(coeffs1[1])
level1 = pd.concat([l1a,l1b],axis = 1)
level1.head()

0           1           2           3           4           5   \
0  -41.095548  -31.430237  137.869903  313.356008  273.795342  194.526981   
1  324.099607  376.203102  437.021300  461.540422  523.962667  553.173799   
2 -135.190198 -113.438871  -57.771677  -55.133441  -56.792090  -45.094706   
3 -105.093271 -137.808679 -135.680619 -128.271953 -140.959019 -148.568680   
4  -98.040668   -8.607662  -46.443293 -145.141724  -94.198610  -17.759042   

           6           7           8           9   ...         86        87  \
0  306.846225  294.093704  113.220097  -40.770710  ... -13.480340 -0.484644   
1  513.374694  460.897510  441.526575  352.724423  ...  -1.553937 -0.963599   
2  -63.242710  -43.430550  -69.814035 -114.867459  ...   1.638419  0.306239   
3 -138.895183 -125.941956 -143.178989 -130.701952  ...   1.070998  6.004320   
4 -124.272186 -127.375114  -31.441067  -17.563886  ...  -1.287863 -6.045401   

         88         89         90        91        92        93        94  \
0 -1.641308  10.391604  -6.757924 -3.714347  3.362450  6.500748 -1.722507   
1 -0.431986 -36.871038  29.920280  9.188612  1.718706 -3.909316  2.732875   
2 -2.255330  13.914152 -10.045778 -3.756084  1.845044 -1.958554  0.159008   
3 -2.826889  20.857737 -16.534617 -4.310068 -1.397633 -3.845873  1.149839   
4  2.548793  13.867954 -12.772237 -0.821887 -2.190610  9.565353 -6.100994   

         95  
0 -8.910678  
1  1.324159  
2  2.520362  
3  0.233967  
4 -0.275595  

[5 rows x 192 columns]

In [ ]:
#random forest
X = level1
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

In [ ]:
#SVM 
X = level1
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = level1
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

In [12]:
#FOR LEVEL 2
l2a= pd.DataFrame(coeffs2[0])
l2b= pd.DataFrame(coeffs2[1])
l2c= pd.DataFrame(coeffs2[2])
level2 = pd.concat([l2a,l2b,l2c],axis = 1)
level2.head()

0           1           2           3           4           5   \
0  -70.736078  345.641360  337.021060  417.861680   75.013283 -133.380882   
1  508.106933  634.848856  763.940573  701.138676  550.108425  464.556012   
2 -166.178915  -82.485488  -79.770522  -63.066290 -134.937928 -198.928307   
3 -178.593860 -185.351449 -204.146701 -194.298096 -181.421084 -161.869395   
4  -40.535466 -154.773030  -90.232805 -147.702677  -78.712394  -77.424025   

           6           7           8           9   ...         86        87  \
0  190.476552  323.149591  445.739391  225.228820  ... -13.480340 -0.484644   
1  566.179830  721.580211  769.902599  550.185139  ...  -1.553937 -0.963599   
2 -110.230203  -78.730247  -67.404850  -91.975099  ...   1.638419  0.306239   
3 -182.056372 -202.291439 -190.970187 -201.648457  ...   1.070998  6.004320   
4 -114.689809  -88.943046 -175.661128  -41.524597  ...  -1.287863 -6.045401   

         88         89         90        91        92        93        94  \
0 -1.641308  10.391604  -6.757924 -3.714347  3.362450  6.500748 -1.722507   
1 -0.431986 -36.871038  29.920280  9.188612  1.718706 -3.909316  2.732875   
2 -2.255330  13.914152 -10.045778 -3.756084  1.845044 -1.958554  0.159008   
3 -2.826889  20.857737 -16.534617 -4.310068 -1.397633 -3.845873  1.149839   
4  2.548793  13.867954 -12.772237 -0.821887 -2.190610  9.565353 -6.100994   

         95  
0 -8.910678  
1  1.324159  
2  2.520362  
3  0.233967  
4 -0.275595  

[5 rows x 204 columns]

In [ ]:
#random_forest
X = level2
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

In [ ]:
#SVM 
X = level2
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = level2
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

In [13]:
# FOR LEVEL 3
l3a= pd.DataFrame(coeffs3[0])
l3b= pd.DataFrame(coeffs3[1])
l3c= pd.DataFrame(coeffs3[2])
l3d= pd.DataFrame(coeffs3[3])
level3 = pd.concat([l3a,l3b,l3c,l3d],axis = 1)
level3.head()

0            1           2           3           4           5   \
0  256.208887   565.572109  -76.827219  452.203687  376.586017  -44.518639   
1  841.831849  1034.679264  671.241991  972.296839  932.356968  704.469632   
2 -171.136924   -91.256309 -243.775985 -119.382168 -136.030737 -227.423102   
3 -258.544721  -282.836218 -237.623252 -274.214335 -270.635691 -247.605611   
4 -150.620536  -174.557107 -115.641828 -166.304102 -153.904905  -92.262130   

            6           7           8           9   ...         86        87  \
0   610.636002  132.334318  151.080011  496.264557  ... -13.480340 -0.484644   
1  1066.213988  760.914324  898.103089  771.324154  ...  -1.553937 -0.963599   
2   -81.642666 -193.326295 -200.833662  -68.225467  ...   1.638419  0.306239   
3  -285.711953 -252.290788 -252.447354 -283.902404  ...   1.070998  6.004320   
4  -180.846085 -134.202978 -134.202571 -176.822227  ...  -1.287863 -6.045401   

         88         89         90        91        92        93        94  \
0 -1.641308  10.391604  -6.757924 -3.714347  3.362450  6.500748 -1.722507   
1 -0.431986 -36.871038  29.920280  9.188612  1.718706 -3.909316  2.732875   
2 -2.255330  13.914152 -10.045778 -3.756084  1.845044 -1.958554  0.159008   
3 -2.826889  20.857737 -16.534617 -4.310068 -1.397633 -3.845873  1.149839   
4  2.548793  13.867954 -12.772237 -0.821887 -2.190610  9.565353 -6.100994   

         95  
0 -8.910678  
1  1.324159  
2  2.520362  
3  0.233967  
4 -0.275595  

[5 rows x 216 columns]

In [ ]:
#random forest
X = level3
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

In [ ]:
#SVM 
X = level3
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = level3
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

In [14]:
# FOR LEVEL 4
l4a = pd.DataFrame(coeffs4[0])
l4b = pd.DataFrame(coeffs4[1])
l4c = pd.DataFrame(coeffs4[2])
l4d = pd.DataFrame(coeffs4[3])
l4e = pd.DataFrame(coeffs4[4])
level4 = pd.concat([l4a,l4b,l4c,l4d,l4e],axis = 1)
level4.head()

0            1            2            3            4   \
0   402.116956   407.991994   389.436652   363.643198   398.915977   
1  1118.584076  1241.906164  1243.280998  1223.482425  1230.289523   
2  -231.954113  -224.708914  -220.585869  -231.777576  -226.658121   
3  -367.493814  -370.822603  -377.107808  -370.271378  -370.681724   
4  -212.105715  -215.897459  -189.139893  -204.282832  -212.473937   

            5            6            7            8            9   ...  \
0   507.335071   399.939514   351.161058   402.756801   402.219677  ...   
1  1278.107934  1238.257281  1232.066298  1097.480626  1742.279441  ...   
2  -204.666818  -228.321629  -227.334367  -231.071218  -198.416765  ...   
3  -377.421403  -369.222356  -374.125300  -369.599607  -385.121571  ...   
4  -222.120970  -218.100129  -190.233652  -206.593802  -196.639496  ...   

          86        87        88         89         90        91        92  \
0 -13.480340 -0.484644 -1.641308  10.391604  -6.757924 -3.714347  3.362450   
1  -1.553937 -0.963599 -0.431986 -36.871038  29.920280  9.188612  1.718706   
2   1.638419  0.306239 -2.255330  13.914152 -10.045778 -3.756084  1.845044   
3   1.070998  6.004320 -2.826889  20.857737 -16.534617 -4.310068 -1.397633   
4  -1.287863 -6.045401  2.548793  13.867954 -12.772237 -0.821887 -2.190610   

         93        94        95  
0  6.500748 -1.722507 -8.910678  
1 -3.909316  2.732875  1.324159  
2 -1.958554  0.159008  2.520362  
3 -3.845873  1.149839  0.233967  
4  9.565353 -6.100994 -0.275595  

[5 rows x 229 columns]

In [ ]:
#random forest
X = level4
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

In [ ]:
#SVM 
X = level4
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = level4
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

In [17]:
# FOR LEVEL 5
l5a = pd.DataFrame(coeffs5[0])
l5b = pd.DataFrame(coeffs5[1])
l5c = pd.DataFrame(coeffs5[2])
l5d = pd.DataFrame(coeffs5[3])
l5e = pd.DataFrame(coeffs5[4])
l5f = pd.DataFrame(coeffs5[5])
level5 = pd.concat([l5a,l5b,l5c,l5d,l5e,l5f],axis = 1)
level5.head()

0            1            2            3            4   \
0   562.448228   512.362693   647.629257   542.330939   557.944973   
1  1512.702287  1725.793621  1772.181106  1760.705534  1714.085419   
2  -324.221782  -324.473845  -305.881437  -319.159444  -319.622374   
3  -520.346921  -526.258116  -527.400829  -527.714606  -526.075336   
4  -293.032299  -279.404567  -314.302192  -285.149094  -289.784094   

            5            6            7            8            9   ...  \
0   591.329945   517.293630   611.268315   570.882327   605.368151  ...   
1  1623.110988  1713.744041  1876.952688  1398.828274  2486.754856  ...   
2  -323.237384  -324.469529  -306.629946  -323.988808  -301.000191  ...   
3  -520.431747  -526.809741  -529.264609  -520.279655  -544.131118  ...   
4  -307.882906  -278.332080  -302.376063  -299.030956  -289.252753  ...   

          86        87        88         89         90        91        92  \
0 -13.480340 -0.484644 -1.641308  10.391604  -6.757924 -3.714347  3.362450   
1  -1.553937 -0.963599 -0.431986 -36.871038  29.920280  9.188612  1.718706   
2   1.638419  0.306239 -2.255330  13.914152 -10.045778 -3.756084  1.845044   
3   1.070998  6.004320 -2.826889  20.857737 -16.534617 -4.310068 -1.397633   
4  -1.287863 -6.045401  2.548793  13.867954 -12.772237 -0.821887 -2.190610   

         93        94        95  
0  6.500748 -1.722507 -8.910678  
1 -3.909316  2.732875  1.324159  
2 -1.958554  0.159008  2.520362  
3 -3.845873  1.149839  0.233967  
4  9.565353 -6.100994 -0.275595  

[5 rows x 242 columns]

In [16]:
#random forest
X = level5
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

NameError: name 'level5' is not defined

In [ ]:
#SVM 
X = level5
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = level5
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

In [18]:
# FOR LEVEL 6
l6a = pd.DataFrame(coeffs6[0])
l6b = pd.DataFrame(coeffs6[1])
l6c = pd.DataFrame(coeffs6[2])
l6d = pd.DataFrame(coeffs6[3])
l6e = pd.DataFrame(coeffs6[4])
l6f = pd.DataFrame(coeffs6[5])
l6g = pd.DataFrame(coeffs6[6])
level6 = pd.concat([l6a,l6b,l6c,l6d,l6e,l6f,l6g],axis = 1)
level6.head()

0            1            2            3            4   \
0   751.790372   820.498639   782.408864   821.551670   805.934634   
1  2213.475813  2499.197594  2343.352621  2505.337491  2401.353071   
2  -454.464761  -443.262639  -458.995818  -445.011890  -449.442441   
3  -733.872263  -746.811011  -739.656023  -746.144564  -743.209294   
4  -406.914091  -416.616044  -414.508555  -418.702397  -415.913573   

            5            6            7            8            9   ...  \
0   763.294209   821.547337   806.904194   777.786640   855.828262  ...   
1  2173.151372  2495.680362  2464.722322  2175.379962  3027.418582  ...   
2  -462.198942  -443.518453  -450.457606  -460.163657  -436.739178  ...   
3  -736.506066  -746.695743  -742.468875  -740.842497  -749.494950  ...   
4  -407.039717  -417.694232  -418.017148  -410.308744  -428.765693  ...   

          86        87        88         89         90        91        92  \
0 -13.480340 -0.484644 -1.641308  10.391604  -6.757924 -3.714347  3.362450   
1  -1.553937 -0.963599 -0.431986 -36.871038  29.920280  9.188612  1.718706   
2   1.638419  0.306239 -2.255330  13.914152 -10.045778 -3.756084  1.845044   
3   1.070998  6.004320 -2.826889  20.857737 -16.534617 -4.310068 -1.397633   
4  -1.287863 -6.045401  2.548793  13.867954 -12.772237 -0.821887 -2.190610   

         93        94        95  
0  6.500748 -1.722507 -8.910678  
1 -3.909316  2.732875  1.324159  
2 -1.958554  0.159008  2.520362  
3 -3.845873  1.149839  0.233967  
4  9.565353 -6.100994 -0.275595  

[5 rows x 254 columns]

In [ ]:
#random forest
X = level6
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

In [ ]:
#SVM 
X = level6
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX : ")
print(cm)
accuracy_score(y_test,y_pred)

In [ ]:
#KNN
X = level6
y = data["OUTPUT_LABEL"] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

# Applying Cross Validation in every coeffs

MERGING EVERY LEVELS DATAFRAME

In [19]:
Merged=pd.concat([level1,level2,level3,level4,level5,level6],axis = 1)

In [20]:
X = Merged
y = data["OUTPUT_LABEL"]

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=10)
for train_index, test_index in kf.split(X):
    print(train_index, test_index)
X_train = pd.DataFrame(train_index)
X_test = pd.DataFrame(test_index)
y_train, y_test = train_test_split(y, test_size=0.1, random_state=42)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

[ 1150  1151  1152 ... 11497 11498 11499] [   0    1    2 ... 1147 1148 1149]
[    0     1     2 ... 11497 11498 11499] [1150 1151 1152 ... 2297 2298 2299]
[    0     1     2 ... 11497 11498 11499] [2300 2301 2302 ... 3447 3448 3449]
[    0     1     2 ... 11497 11498 11499] [3450 3451 3452 ... 4597 4598 4599]
[    0     1     2 ... 11497 11498 11499] [4600 4601 4602 ... 5747 5748 5749]
[    0     1     2 ... 11497 11498 11499] [5750 5751 5752 ... 6897 6898 6899]
[    0     1     2 ... 11497 11498 11499] [6900 6901 6902 ... 8047 8048 8049]
[    0     1     2 ... 11497 11498 11499] [8050 8051 8052 ... 9197 9198 9199]
[    0     1     2 ... 11497 11498 11499] [ 9200  9201  9202 ... 10347 10348 10349]
[    0     1     2 ... 10347 10348 10349] [10350 10351 10352 ... 11497 11498 11499]


0.8017391304347826

In [22]:
Merged.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            86, 87, 88, 89, 90, 91, 92, 93, 94, 95],
           dtype='int64', length=1337)

In [23]:
Merged.index

RangeIndex(start=0, stop=11500, step=1)

In [24]:
n = int(input("enter the no of population:-"))

enter the no of population:-5


In [27]:
random_pop = np.random.choice([0, 1], size=[n,1336], replace=True)
random_pop

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 0, 0, 1]])

In [28]:
len(random_pop[0])

1336

In [29]:
random_pop.shape

(5, 1336)

In [30]:
fit_list = []

In [31]:
gbest_list = []
for l in range(0,n):
    dfaa = pd.DataFrame()
    for k in range(0,1336):
        if(random_pop[l,k]==1):
            listA = (Merged.iloc[:,k])
            dfa = pd.DataFrame(listA)
            dfaa = dfaa.join(dfa,how = 'right',rsuffix='right')
    X = dfaa
    y = data["OUTPUT_LABEL"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
    rf = RandomForestClassifier(n_estimators=50)
    rf.fit(X_train,y_train)
    predictions = rf.predict(X_test)
    fit_list.append(accuracy_score(y_test,predictions))
gbest = max(fit_list)
ind = fit_list.index(max(fit_list))
gbest_pop = random_pop[ind]


#for a in range(0,itn):
    #Improving phase
    #fit_listIMP = []
    #for l in range(0,n):
        #dfaa = pd.DataFrame()
        #for k in range(0,24):
            #if(random[l,k]==1):
                #listA = (data[:][k])
                #dfa = pd.DataFrame(listA)
                #dfaa = dfaa.join(dfa,how = 'right')
        #X = dfaa
        #y = data[24]
        #X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
        #rf = RandomForestClassifier(n_estimators=50)
        #rf.fit(X_train,y_train)
        #predictions = rf.predict(X_test)
    #fit_list.append(accuracy_score(y_test,predictions))
#gbest_new = max(fit_list)
#if(gbest_new > gbest):
    #gbest = gbest_new
    #ind = fit_list.index(max(fit_list))
    #gbest_pop = random[ind]
#gbest_list.append(gbest)

In [32]:
fit_list

[0.9744927536231884,
 0.9701449275362319,
 0.9742028985507246,
 0.9698550724637681,
 0.9773913043478261]

In [33]:
gbest

0.9773913043478261

In [34]:
gbest_pop

array([1, 1, 1, ..., 0, 0, 1])

In [35]:
fit_list_imp = fit_list

In [36]:
fit_list_imp

[0.9744927536231884,
 0.9701449275362319,
 0.9742028985507246,
 0.9698550724637681,
 0.9773913043478261]

In [37]:
c=0.2

In [38]:
imp_pop = random_pop

In [39]:
import random

In [43]:
for r in range(0,n):
    X1 = pd.DataFrame()
    X_new = np.random.choice([0, 1], size=[1,1336], replace=True)
    for d in range(0,1336):
        a1 = random_pop[r][d]
        b1 = gbest_pop[d]
        f = random.random()
        X_new[0][d] = c*a1 + f*(b1 - a1)
        X_new[0][d] = int(round(abs(X_new[0][d])))
        if(X_new[0][d] > 0):
            X_new[0][d] = 1
    for k in range(0,24):
        if(X_new[0][k]==1):
            listB = (data[:][k])
            df = pd.DataFrame(listB)
            X1 = X1.join(df,how = 'right')

In [62]:
X_new = np.random.choice([0, 1], size=[1,1336], replace=True)
print("X_new : "  , X_new)
X_new.shape

X_new :  [[1 0 0 ... 0 1 1]]


(1, 1336)

In [80]:
for q in range(0,1):
    for w in range(0,1336):
        a=random_pop[q][w]
        b=gbest_pop[w]
        d=random.random()
        X_new[0][w] = c*a + d*(b - a)

In [83]:
X_new

array([[0, 0, 0, ..., 0, 0, 0]])